# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

julia:
  - 1.3
  - 1.4
  - nightly

os:
  - linux
  - osx

env:
  global:
    - JULIA_TRACK_COVERAGE=yes

# Force Ubuntu 18.04 "Bionic" to get even newer GCC, binutils etc.
dist: bionic

before_install:
# - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi # sudo apt-get install -y libglpk-dev;
# - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi # brew install glpk;

jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  include:
    - stage: Documentation
      name: "HTML"
      julia: 1.3
      script: travis_wait 60 julia --color=yes --project=docs -e '
          using Pkg;
          Pkg.instantiate();
          Pkg.develop(PackageSpec(path=pwd()));
          include(joinpath("docs","make.jl"));'
      after_success: skip

notifications:
  email:
    recipients:
      - mohamed.barakat@uni-siegen.de
    on_success: never   # default: change
    on_failure: always  # default: always
